// 模拟权限数据
export const mockPermissionData = {
    sideMenus:[
        {
            title:'菜单1',
            name:'name1',
            childMenus:[
                {
                    title:'1子菜单1',
                    name:'child1'
                },
                 {
                    title:'1子菜单2',
                    name:'child2'
                }
            ]
        },
         {
            title:'菜单2',
            name:'name2',
            childMenus:[
                {
                    title:'1子菜单1',
                    name:'child3'
                },
                 {
                    title:'1子菜单2',
                    name:'child4'
                }
            ]
        }
    ],
    navMenus:[
        {
            title:'用户管理企业会员',
            name:'user1'
        },
        {
            title:'门店会员',
            name:'user2'
        },
        {
            title:'礼卷维护',
            name:'user3'
        }, {
            title:'商品维护',
            name:'user4'
        }
    ],
    perimissionData:[
        {
            title:'是否可以添加用户',
            code:'AddUserPerimisson'
        },
        {
            title:'是否可以添加商店',
            code:'AddUserPerimisson1'
        },
        {
            title:'是否可以添加礼卷',
            code:'AddUserPerimisson2'
        },
    ]
}