export const mockTableColumns = [
    {
        title:'商家名称',
        key:'title'
    },
    {
        title:'拥有人',
        key:'owner'
    },
    {
        title:'创建日期',
        key:'createDate'
    },
]
export const mockTableData = [
    {
        title:'商家A',
        owner:'A',
        createDate:'2019-02-13'
    },
    {
        title:'商家A434',
        owner:'A32',
        createDate:'2019-02-23'
    },
    {
        title:'商家A22',
        owner:'A33',
        createDate:'2019-03-03'
    },
]
// 模拟权限数据
export const mockPermissionData = {
    sideMenus:[
        {
            title:'基础组件',
            name:'name1',
            childMenus:[
                {
                    title:'表格',
                    name:'basicTable'
                },
                 {
                    title:'1子菜单2',
                    name:'child2'
                }
            ]
        },
         {
            title:'菜单2',
            name:'name2',
            childMenus:[
                {
                    title:'1子菜单1',
                    name:'child3'
                },
                 {
                    title:'1子菜单2',
                    name:'child4'
                }
            ]
        }
    ],
    navMenus:[
        {
            title:'用户管理企业会员',
            name:'user1'
        },
        {
            title:'门店会员',
            name:'user2'
        },
        {
            title:'礼卷维护',
            name:'user3'
        }, {
            title:'商品维护',
            name:'user4'
        }
    ],
    perimissionData:[
        {
            title:'是否可以添加用户',
            code:'AddUserPerimisson'
        },
        {
            title:'是否可以添加商店',
            code:'AddUserPerimisson1'
        },
        {
            title:'是否可以添加礼卷',
            code:'AddUserPerimisson2'
        },
    ]
}